name: Rust Project CI

on:
  push:
    branches: [ "main", "dev" ] # Runs on push to main or dev
  pull_request:
    branches: [ "main" ] # Runs on pull requests to main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_linux:
    name: Build and Test (Ubuntu)
    runs-on: ubuntu-latest # This is the magic line!
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Linux dependencies
      # This is needed for Iced/wgpu on a fresh Ubuntu server
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libasound2-dev libudev-dev

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose